import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ProjectPermissionGuard } from 'src/auth/guards';
import { CommonModule } from 'src/common/common.module';
import { OutboxModule } from 'src/outbox/outbox.module';
import { NotificationsModule } from 'src/notifications/notifications.module';
import {
  Project,
  ProjectActivityLog,
  ProjectInvite,
  ProjectMembership,
  ProjectRole,
} from 'src/projects/entities';
import { User } from 'src/users/entities';
import { WorkspaceMember } from 'src/workspaces/entities';
import {
  ProjectLabel,
  ProjectPriority,
  ProjectSeverity,
  ProjectStatus,
  ProjectTaskType,
} from './project-config';
import {
  ProjectCalendar,
  ProjectCalendarException,
  Task,
  TaskActivityLog,
  TaskActivitySchedule,
  TaskAssignee,
  TaskChecklist,
  TaskChecklistItem,
  TaskComment,
  TaskDependency,
  TaskDocument,
  TaskDocumentAttachment,
  TaskLabel,
  TaskMaterial,
  TaskRelation,
  TaskResourceAllocation,
  TaskScheduleCalculationRun,
  TaskScheduleExplanation,
  TaskScheduleOverride,
  TaskViewMetadata,
  TaskWatcher,
} from './entities';
import { TasksController } from './tasks.controller';
import { TasksService } from './tasks.service';
import {
  ActivityScheduleGanttService,
  ActivityScheduleImportService,
  ActivityScheduleQueryService,
  ProjectCalendarService,
  ScheduleCalculationService,
  TaskActivityScheduleService,
  TaskActivityService,
  TaskAuthService,
  TaskChecklistService,
  TaskCommentsService,
  TaskCrudService,
  TaskDocumentsService,
  TaskMembersService,
  TaskMaterialsReportImportService,
  TaskMaterialsReportService,
  TaskMaterialsService,
  TaskQueryService,
  TaskRankingService,
  TaskRelationsService,
  TaskResourceAllocationService,
  TaskResourceReportImportService,
  TaskResourceReportService,
} from './services';

const SUB_SERVICES = [
  TaskAuthService,
  ActivityScheduleGanttService,
  ActivityScheduleImportService,
  ActivityScheduleQueryService,
  ProjectCalendarService,
  ScheduleCalculationService,
  TaskActivityScheduleService,
  TaskActivityService,
  TaskRankingService,
  TaskCommentsService,
  TaskChecklistService,
  TaskRelationsService,
  TaskMembersService,
  TaskMaterialsReportImportService,
  TaskMaterialsReportService,
  TaskMaterialsService,
  TaskDocumentsService,
  TaskCrudService,
  TaskQueryService,
  TaskResourceAllocationService,
  TaskResourceReportImportService,
  TaskResourceReportService,
];

@Module({
  imports: [
    TypeOrmModule.forFeature([
      ProjectCalendar,
      ProjectCalendarException,
      Task,
      TaskAssignee,
      TaskActivitySchedule,
      TaskChecklist,
      TaskChecklistItem,
      TaskComment,
      TaskDependency,
      TaskDocument,
      TaskDocumentAttachment,
      TaskLabel,
      TaskMaterial,
      TaskRelation,
      TaskResourceAllocation,
      TaskScheduleCalculationRun,
      TaskScheduleExplanation,
      TaskScheduleOverride,
      TaskViewMetadata,
      TaskWatcher,
      TaskActivityLog,
      Project,
      ProjectInvite,
      ProjectMembership,
      ProjectRole,
      ProjectActivityLog,
      User,
      ProjectStatus,
      ProjectPriority,
      ProjectSeverity,
      ProjectTaskType,
      ProjectLabel,
      WorkspaceMember,
    ]),
    CommonModule,
    NotificationsModule,
    OutboxModule,
  ],
  controllers: [TasksController],
  providers: [TasksService, ProjectPermissionGuard, ...SUB_SERVICES],
  exports: [TasksService],
})
export class TasksModule {}
